apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tylerpitcher-com
  namespace: prod
spec:
  secretName: tylerpitcher-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - www.tylerpitcher.com
    - tylerpitcher.com
